# Railway project configuration
[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment configuration
[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
