# Railway project configuration
[build]
builder = "nixpacks"
nixpacksPlan = '{ "phases": { "setup": { "nixPkgs": ["dotnet-sdk_8"] } } }'

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment configuration
[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
