# Railway project configuration
[build]
builder = "NIXPACKS"
buildCommand = "dotnet publish Server.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/Server.dll"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment configuration
[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
