# Railway project configuration for .NET 8
[build]
builder = "nixpacks"
buildCommand = "dotnet publish Server.csproj -c Release -o ./out"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/health"

# Environment configuration
[deploy.env]
ASPNETCORE_ENVIRONMENT = "Production"
PORT = "8080"
ASPNETCORE_URLS = "http://+:8080"

# Specify .NET 8.0 SDK
[nixpacks]
pkgs = ["dotnet-sdk_8"]
